### ISSUE TITLE
modules - java.desktop dependency?

### ISSUE THREAD

**Issue by ryanhamilton** [webcompere/lightweight-config#13]
Hi,

I'm using your library in our product: https://www.timestored.com/pulse/

Currently I am trying to bundle our tool with a reduced JRE using java 9 modules. Two issues:
1. Your library doesn't include a module-info.java (not breaking, just a warning)
2. Your library seems to rely on snakeyaml which relied on java.desktop module. I get the below stack trace when I include your library. I only get this error if I remove the java.desktop module. The desktop module mostly includes swing/awt and is quite large. Since mine is not a graphical java program I would really like to remove that large depency to remove 10MB from the bundled JRE.

It's up to you, maybe most your users are not trying to bundle a reduced JRE.
Thanks again for a useful library,
Ryan

```
Exception in thread "main" java.lang.NoClassDefFoundError: java/beans/IntrospectionException
        at org.yaml.snakeyaml.representer.BaseRepresenter.getPropertyUtils(BaseRepresenter.java:202)
        at uk.org.webcompere.lightweightconfig.ConfigLoader.getYaml(ConfigLoader.java:205)
        at uk.org.webcompere.lightweightconfig.ConfigLoader.loadAs(ConfigLoader.java:117)
        at uk.org.webcompere.lightweightconfig.ConfigLoader.loadYmlConfigFromResource(ConfigLoader.java:43)
        at com.sqldashboards.webby.Application.forceConfigReload(Application.java:124)
        at com.sqldashboards.webby.Application.<clinit>(Application.java:45)
Caused by: java.lang.ClassNotFoundException: java.beans.IntrospectionException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
```

**Comment by ryanhamilton** [comment]
Actually I investigated a little and it seems the problem is much much wider:
https://github.com/spring-projects/spring-framework/issues/26884
I can't take advantage of your fix unless spring itself improves :(

**Comment by ashleyfrieze** [comment]
I don't think snakeyml uses java.desktop - https://bitbucket.org/snakeyaml/snakeyaml/src/master/pom.xml - it seems to have no major dependencies.

If you're using Spring, why do you need this package? Spring has its own rich configuration system.

**Comment by ashleyfrieze** [comment]
There is no dependency on `java.desktop`, though your IDE may include that in your project - this is what's pulled in by maven 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/5574729/214911484-f2be7f46-932d-4f92-ad5d-fb3d78541108.png">

**Comment by ashleyfrieze** [comment]
In the interests of keeping this project viable, I'm releasing v1.2.1 - this has the latest snakeyml, which should hopefully be as compatible as possible with the latest JDKs etc. I've rebuilt the project against JDK17.

**Comment by ryanhamilton** [comment]
Thank you.

**Comment by ashleyfrieze** [comment]
#17 contains the latest snakeyaml upgrade
